### PR TITLE
Update for bevy 0.10.0

### PR DESCRIPTION
**Pull request by campbellcole**
Also adds development support for NixOS, can remove if wanted.

I bumped the version to 0.2.0 because this is a breaking version, but up to you how you want to handle versioning.

### CODE REVIEW

**Comment by campbellcole** [comment]
I just learned about the `PrimaryWindow` component, updating this PR to use that instead of just getting the first window from the query.

**Comment by rdelfin** [comment]
Thanks @campbellcole! I somehow didn't see this PR. Let me test it out and merge :smile:

**Comment by rdelfin** [comment]
@campbellcole could you remove the nix files, `.envrc`, and the version bump? Happy to add the nix stuff in a separate PR. I'll also version bump separately so I can publish the crate out and add to the README.

**Comment by rdelfin** [comment]
Merged separately, closing

**Pull request closed without merging**
